FROM jenkins/ssh-agent:latest

RUN apt update -y &&\
 apt install -y maven gradle npm &&\
 sed -i 's/[#]?ClientAliveInterval.*/ClientAliveInterval 1200/' /etc/ssh/sshd_config &&\
 sed -i 's/[#]?ClientAliveCountMax.*/ClientAliveCountMax 3/' /etc/ssh/sshd_config
