FROM jenkins/ssh-agent:latest
USER root
RUN apt-get update -y -q &&\
    apt-get install -y -q  maven gradle npm &&\
    apt-get autoremove -y -q &&\
    apt-get clean -y -q &&\
    sed -i 's/[#]?ClientAliveInterval.*/ClientAliveInterval 1200/' /etc/ssh/sshd_config &&\
    sed -i 's/[#]?ClientAliveCountMax.*/ClientAliveCountMax 3/' /etc/ssh/sshd_config

#apt-get upgrade -y -q &&\
