FROM jenkins/inbound-agent:latest
USER root
RUN apt-get update -y -q &&\
    apt-get remove docker docker-engine docker.io containerd runc &&\
    apt-get install -y -q  maven gradle npm ca-certificates curl gnupg lsb-release &&\
    mkdir -p /etc/apt/keyrings &&\
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&\
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&\
    apt-get update -y -q &&\
    sudo apt-get -y -q install docker-ce docker-ce-cli containerd.io docker-compose-plugin &&\
    apt-get autoremove -y -q &&\
    apt-get clean -y -q &&\

#apt-get upgrade -y -q &&\
