# -*- mode: ruby -*-
# vi: set ft=ruby :

# Run from cli to have files sync:
# vagrant rsync-auto

VAGRANTFILE_API_VERSION = "2"
HOSTNAME = "docker-env"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
end

  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    #master.vm.box = "alpine/alpine64"
    master.vm.hostname = "master"
    master.vm.provider :virtualbox do |vb|
      #vb.gui = true
      #vb.name = HOSTNAME
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--description", "docker environment"]
    end

    master.vm.network "private_network", ip: "192.168.200.200"
    master.vm.synced_folder ".", "/vagrant", type: "rsync", create: "true"
    master.vm.network "forwarded_port", guest: 80, host: 50080
    # Main port
    master.vm.network "forwarded_port", guest: 8080, host: 58080
    master.vm.network "forwarded_port", guest: 443, host: 50443
    master.vm.network "forwarded_port", guest: 22, host: 50022

    master.vm.provision "shell", inline: <<-SHELL
      cd /vagrant/master
      chmod +x *.sh
      sh setup.sh
    SHELL

  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "centos/7"
    #agent1.vm.box = "alpine/alpine64"
    agent1.vm.hostname = "agent1"
    agent1.vm.provider :virtualbox do |vb|
      #vb.gui = true
      #vb.name = HOSTNAME
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--description", "docker environment"]
    end

    agent1.vm.network "private_network", ip: "192.168.200.201"
    agent1.vm.synced_folder ".", "/vagrant", type: "rsync", create: "true"
    agent1.vm.network "forwarded_port", guest: 22, host: 40022

    agent1.vm.provision "shell", inline: <<-SHELL
      cd /vagrant/agent
      chmod +x *.sh
      sh setup.sh
    SHELL

  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "centos/7"
    #agent2.vm.box = "alpine/alpine64"
    agent2.vm.hostname = "agent2"
    agent2.vm.provider :virtualbox do |vb|
      #vb.gui = true
      #vb.name = HOSTNAME
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--description", "docker environment"]
    end

    agent2.vm.network "private_network", ip: "192.168.200.202"
    agent2.vm.synced_folder ".", "/vagrant", type: "rsync", create: "true"
    agent2.vm.network "forwarded_port", guest: 22, host: 30022

    agent2.vm.provision "shell", inline: <<-SHELL
      cd /vagrant/agent
      chmod +x *.sh
      sh setup.sh
    SHELL

  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.compatibility_mode = "2.0"
#    ansible.playbook = "provisioning/main.yml"
#  end

end

